
 const books=[
  {
    "id": 1,
    "title": "Book Title 1",
    "author": "Author 1",
    "year": 1932,
    "genre": "Sci-Fi",
    "pages": 165,
    "irating": 3.59,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 1. It covers the genre Fantasy and is written by Author 1."
  },
  {
    "id": 2,
    "title": "Book Title 2",
    "author": "Author 2",
    "year": 2000,
    "genre": "Sci-Fi",
    "pages": 427,
    "irating": 1.61,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 2. It covers the genre Thriller and is written by Author 2."
  },
  {
    "id": 3,
    "title": "Book Title 3",
    "author": "Author 3",
    "year": 1926,
    "genre": "Fantasy",
    "pages": 466,
    "irating": 4.01,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 3. It covers the genre Romantic and is written by Author 3."
  },
  {
    "id": 4,
    "title": "Book Title 4",
    "author": "Author 4",
    "year": 1906,
    "genre": "Horror",
    "pages": 360,
    "irating": 1.18,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 4. It covers the genre Mystery and is written by Author 4."
  },
  {
    "id": 5,
    "title": "Book Title 5",
    "author": "Author 5",
    "year": 2004,
    "genre": "Sci-Fi",
    "pages": 417,
    "irating": 3.9,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 5. It covers the genre Adventure and is written by Author 5."
  },
  {
    "id": 6,
    "title": "Book Title 6",
    "author": "Author 6",
    "year": 1934,
    "genre": "Comic",
    "pages": 375,
    "irating": 3.72,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 6. It covers the genre Fiction and is written by Author 6."
  },
  {
    "id": 7,
    "title": "Book Title 7",
    "author": "Author 7",
    "year": 1959,
    "genre": "Comic",
    "pages": 505,
    "irating": 1.37,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 7. It covers the genre Fiction and is written by Author 7."
  },
  {
    "id": 8,
    "title": "Book Title 8",
    "author": "Author 8",
    "year": 1992,
    "genre": "Fantasy",
    "pages": 248,
    "irating": 4.21,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 8. It covers the genre Romantic and is written by Author 8."
  },
  {
    "id": 9,
    "title": "Book Title 9",
    "author": "Author 9",
    "year": 1933,
    "genre": "Fiction",
    "pages": 427,
    "irating": 4.56,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 9. It covers the genre Romantic and is written by Author 9."
  },
  {
    "id": 10,
    "title": "Book Title 10",
    "author": "Author 10",
    "year": 1905,
    "genre": "Adventure",
    "pages": 335,
    "irating": 4.61,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 10. It covers the genre Romantic and is written by Author 10."
  },
  {
    "id": 11,
    "title": "Book Title 11",
    "author": "Author 11",
    "year": 1933,
    "genre": "Thriller",
    "pages": 191,
    "irating": 4.06,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 11. It covers the genre Mystery and is written by Author 11."
  },
  {
    "id": 12,
    "title": "Book Title 12",
    "author": "Author 12",
    "year": 1986,
    "genre": "Sci-Fi",
    "pages": 568,
    "irating": 3.61,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 12. It covers the genre Sci-Fi and is written by Author 12."
  },
  {
    "id": 13,
    "title": "Book Title 13",
    "author": "Author 13",
    "year": 1944,
    "genre": "Fantasy",
    "pages": 176,
    "irating": 4.02,
    "imageUrl": "https://i.imgur.com/5A5A5A5.jpg",
    "description": "This is a dummy description for Book Title 13. It covers the genre Fantasy and is written by Author 13."
  },
  {
    "id": 14,
    "title": "Book Title 14",
    "author": "Author 14",
    "year": 1963,
    "genre": "Horror",
    "pages": 700,
    "irating": 1.21,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 14. It covers the genre Comic and is written by Author 14."
  },
  {
    "id": 15,
    "title": "Book Title 15",
    "author": "Author 15",
    "year": 1986,
    "genre": "Romantic",
    "pages": 640,
    "irating": 4.83,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 15. It covers the genre Comic and is written by Author 15."
  },
  {
    "id": 16,
    "title": "Book Title 16",
    "author": "Author 16",
    "year": 1947,
    "genre": "Romantic",
    "pages": 509,
    "irating": 3.19,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 16. It covers the genre Thriller and is written by Author 16."
  },
  {
    "id": 17,
    "title": "Book Title 17",
    "author": "Author 17",
    "year": 1929,
    "genre": "Adventure",
    "pages": 543,
    "irating": 2.77,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 17. It covers the genre Adventure and is written by Author 17."
  },
  {
    "id": 18,
    "title": "Book Title 18",
    "author": "Author 18",
    "year": 1982,
    "genre": "Fantasy",
    "pages": 525,
    "irating": 2.91,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 18. It covers the genre Sci-Fi and is written by Author 18."
  },
  {
    "id": 19,
    "title": "Book Title 19",
    "author": "Author 19",
    "year": 2019,
    "genre": "Fantasy",
    "pages": 371,
    "irating": 1.8,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 19. It covers the genre Fiction and is written by Author 19."
  },
  {
    "id": 20,
    "title": "Book Title 20",
    "author": "Author 20",
    "year": 2020,
    "genre": "Thriller",
    "pages": 495,
    "irating": 3.98,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 20. It covers the genre Horror and is written by Author 20."
  },
  {
    "id": 21,
    "title": "Book Title 21",
    "author": "Author 21",
    "year": 1918,
    "genre": "Comic",
    "pages": 539,
    "irating": 4.47,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 21. It covers the genre Thriller and is written by Author 21."
  },
  {
    "id": 22,
    "title": "Book Title 22",
    "author": "Author 22",
    "year": 1991,
    "genre": "Thriller",
    "pages": 101,
    "irating": 1.05,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 22. It covers the genre Fantasy and is written by Author 22."
  },
  {
    "id": 23,
    "title": "Book Title 23",
    "author": "Author 23",
    "year": 1990,
    "genre": "Horror",
    "pages": 494,
    "irating": 3.83,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 23. It covers the genre Romantic and is written by Author 23."
  },
  {
    "id": 24,
    "title": "Book Title 24",
    "author": "Author 24",
    "year": 1947,
    "genre": "Mystery",
    "pages": 367,
    "irating": 2.35,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 24. It covers the genre Thriller and is written by Author 24."
  },
  {
    "id": 25,
    "title": "Book Title 25",
    "author": "Author 25",
    "year": 2006,
    "genre": "Comic",
    "pages": 297,
    "irating": 1.94,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 25. It covers the genre Comic and is written by Author 25."
  },
  {
    "id": 26,
    "title": "Book Title 26",
    "author": "Author 26",
    "year": 1941,
    "genre": "Romantic",
    "pages": 396,
    "irating": 5.0,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 26. It covers the genre Horror and is written by Author 26."
  },
  {
    "id": 27,
    "title": "Book Title 27",
    "author": "Author 27",
    "year": 1995,
    "genre": "Horror",
    "pages": 275,
    "irating": 4.22,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 27. It covers the genre Mystery and is written by Author 27."
  },
  {
    "id": 28,
    "title": "Book Title 28",
    "author": "Author 28",
    "year": 1989,
    "genre": "Adventure",
    "pages": 515,
    "irating": 1.38,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 28. It covers the genre Romantic and is written by Author 28."
  },
  {
    "id": 29,
    "title": "Book Title 29",
    "author": "Author 29",
    "year": 1967,
    "genre": "Fiction",
    "pages": 441,
    "irating": 2.68,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 29. It covers the genre Romantic and is written by Author 29."
  },
  {
    "id": 30,
    "title": "Book Title 30",
    "author": "Author 30",
    "year": 1917,
    "genre": "Mystery",
    "pages": 550,
    "irating": 2.85,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 30. It covers the genre Adventure and is written by Author 30."
  },
  {
    "id": 31,
    "title": "Book Title 31",
    "author": "Author 31",
    "year": 1954,
    "genre": "Comic",
    "pages": 164,
    "irating": 1.95,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 31. It covers the genre Sci-Fi and is written by Author 31."
  },
  {
    "id": 32,
    "title": "Book Title 32",
    "author": "Author 32",
    "year": 1970,
    "genre": "Mystery",
    "pages": 459,
    "irating": 2.57,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 32. It covers the genre Fantasy and is written by Author 32."
  },
  {
    "id": 33,
    "title": "Book Title 33",
    "author": "Author 33",
    "year": 1918,
    "genre": "Horror",
    "pages": 242,
    "irating": 3.41,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 33. It covers the genre Adventure and is written by Author 33."
  },
  {
    "id": 34,
    "title": "Book Title 34",
    "author": "Author 34",
    "year": 2009,
    "genre": "Adventure",
    "pages": 312,
    "irating": 4.1,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 34. It covers the genre Adventure and is written by Author 34."
  },
  {
    "id": 35,
    "title": "Book Title 35",
    "author": "Author 35",
    "year": 1998,
    "genre": "Thriller",
    "pages": 666,
    "irating": 3.06,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 35. It covers the genre Fantasy and is written by Author 35."
  },
  {
    "id": 36,
    "title": "Book Title 36",
    "author": "Author 36",
    "year": 1938,
    "genre": "Fiction",
    "pages": 470,
    "irating": 3.13,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 36. It covers the genre Thriller and is written by Author 36."
  },
  {
    "id": 37,
    "title": "Book Title 37",
    "author": "Author 37",
    "year": 1931,
    "genre": "Sci-Fi",
    "pages": 260,
    "irating": 2.19,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 37. It covers the genre Fantasy and is written by Author 37."
  },
  {
    "id": 38,
    "title": "Book Title 38",
    "author": "Author 38",
    "year": 1921,
    "genre": "Fantasy",
    "pages": 403,
    "irating": 3.08,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 38. It covers the genre Romantic and is written by Author 38."
  },
  {
    "id": 39,
    "title": "Book Title 39",
    "author": "Author 39",
    "year": 2008,
    "genre": "Mystery",
    "pages": 343,
    "irating": 3.19,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 39. It covers the genre Fantasy and is written by Author 39."
  },
  {
    "id": 40,
    "title": "Book Title 40",
    "author": "Author 40",
    "year": 1995,
    "genre": "Mystery",
    "pages": 544,
    "irating": 2.93,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 40. It covers the genre Adventure and is written by Author 40."
  },
  {
    "id": 41,
    "title": "Book Title 41",
    "author": "Author 41",
    "year": 1973,
    "genre": "Fantasy",
    "pages": 379,
    "irating": 3.42,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 41. It covers the genre Fiction and is written by Author 41."
  },
  {
    "id": 42,
    "title": "Book Title 42",
    "author": "Author 42",
    "year": 1983,
    "genre": "Adventure",
    "pages": 548,
    "irating": 1.4,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 42. It covers the genre Romantic and is written by Author 42."
  },
  {
    "id": 43,
    "title": "Book Title 43",
    "author": "Author 43",
    "year": 1986,
    "genre": "Adventure",
    "pages": 472,
    "irating": 3.98,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 43. It covers the genre Mystery and is written by Author 43."
  },
  {
    "id": 44,
    "title": "Book Title 44",
    "author": "Author 44",
    "year": 1955,
    "genre": "Comic",
    "pages": 707,
    "irating": 3.15,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 44. It covers the genre Romantic and is written by Author 44."
  },
  {
    "id": 45,
    "title": "Book Title 45",
    "author": "Author 45",
    "year": 1958,
    "genre": "Romantic",
    "pages": 730,
    "irating": 1.34,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 45. It covers the genre Romantic and is written by Author 45."
  },
  {
    "id": 46,
    "title": "Book Title 46",
    "author": "Author 46",
    "year": 2000,
    "genre": "Adventure",
    "pages": 404,
    "irating": 4.41,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 46. It covers the genre Mystery and is written by Author 46."
  },
  {
    "id": 47,
    "title": "Book Title 47",
    "author": "Author 47",
    "year": 1970,
    "genre": "Fantasy",
    "pages": 140,
    "irating": 1.27,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 47. It covers the genre Sci-Fi and is written by Author 47."
  },
  {
    "id": 48,
    "title": "Book Title 48",
    "author": "Author 48",
    "year": 1971,
    "genre": "Fiction",
    "pages": 706,
    "irating": 2.57,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 48. It covers the genre Romantic and is written by Author 48."
  },
  {
    "id": 49,
    "title": "Book Title 49",
    "author": "Author 49",
    "year": 2023,
    "genre": "Mystery",
    "pages": 404,
    "irating": 1.53,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 49. It covers the genre Mystery and is written by Author 49."
  },
  {
    "id": 50,
    "title": "Book Title 50",
    "author": "Author 50",
    "year": 1923,
    "genre": "Romantic",
    "pages": 149,
    "irating": 1.31,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 50. It covers the genre Horror and is written by Author 50."
  },
  {
    "id": 51,
    "title": "Book Title 51",
    "author": "Author 51",
    "year": 1995,
    "genre": "Comic",
    "pages": 362,
    "irating": 1.07,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 51. It covers the genre Horror and is written by Author 51."
  },
  {
    "id": 52,
    "title": "Book Title 52",
    "author": "Author 52",
    "year": 1946,
    "genre": "Fantasy",
    "pages": 302,
    "irating": 1.83,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 52. It covers the genre Thriller and is written by Author 52."
  },
  {
    "id": 53,
    "title": "Book Title 53",
    "author": "Author 53",
    "year": 1967,
    "genre": "Horror",
    "pages": 544,
    "irating": 1.0,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 53. It covers the genre Comic and is written by Author 53."
  },
  {
    "id": 54,
    "title": "Book Title 54",
    "author": "Author 54",
    "year": 1947,
    "genre": "Mystery",
    "pages": 106,
    "irating": 1.59,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 54. It covers the genre Mystery and is written by Author 54."
  },
  {
    "id": 55,
    "title": "Book Title 55",
    "author": "Author 55",
    "year": 1902,
    "genre": "Romantic",
    "pages": 115,
    "irating": 4.45,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 55. It covers the genre Thriller and is written by Author 55."
  },
  {
    "id": 56,
    "title": "Book Title 56",
    "author": "Author 56",
    "year": 2000,
    "genre": "Sci-Fi",
    "pages": 315,
    "irating": 2.91,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 56. It covers the genre Fantasy and is written by Author 56."
  },
  {
    "id": 57,
    "title": "Book Title 57",
    "author": "Author 57",
    "year": 2016,
    "genre": "Fiction",
    "pages": 104,
    "irating": 2.96,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 57. It covers the genre Horror and is written by Author 57."
  },
  {
    "id": 58,
    "title": "Book Title 58",
    "author": "Author 58",
    "year": 1984,
    "genre": "Mystery",
    "pages": 583,
    "irating": 1.27,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 58. It covers the genre Thriller and is written by Author 58."
  },
  {
    "id": 59,
    "title": "Book Title 59",
    "author": "Author 59",
    "year": 1934,
    "genre": "Romantic",
    "pages": 456,
    "irating": 2.1,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 59. It covers the genre Thriller and is written by Author 59."
  },
  {
    "id": 60,
    "title": "Book Title 60",
    "author": "Author 60",
    "year": 1937,
    "genre": "Fantasy",
    "pages": 321,
    "irating": 4.59,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 60. It covers the genre Horror and is written by Author 60."
  },
  {
    "id": 61,
    "title": "Book Title 61",
    "author": "Author 61",
    "year": 1988,
    "genre": "Horror",
    "pages": 318,
    "irating": 1.17,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 61. It covers the genre Thriller and is written by Author 61."
  },
  {
    "id": 62,
    "title": "Book Title 62",
    "author": "Author 62",
    "year": 1922,
    "genre": "Sci-Fi",
    "pages": 442,
    "irating": 2.18,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 62. It covers the genre Horror and is written by Author 62."
  },
  {
    "id": 63,
    "title": "Book Title 63",
    "author": "Author 63",
    "year": 1914,
    "genre": "Horror",
    "pages": 659,
    "irating": 1.05,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 63. It covers the genre Thriller and is written by Author 63."
  },
  {
    "id": 64,
    "title": "Book Title 64",
    "author": "Author 64",
    "year": 2010,
    "genre": "Horror",
    "pages": 464,
    "irating": 4.64,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 64. It covers the genre Fantasy and is written by Author 64."
  },
  {
    "id": 65,
    "title": "Book Title 65",
    "author": "Author 65",
    "year": 1963,
    "genre": "Adventure",
    "pages": 611,
    "irating": 4.15,
    "imageUrl": "https://i.imgur.com/5A5A5A5.jpg",
    "description": "This is a dummy description for Book Title 65. It covers the genre Romantic and is written by Author 65."
  },
  {
    "id": 66,
    "title": "Book Title 66",
    "author": "Author 66",
    "year": 2005,
    "genre": "Mystery",
    "pages": 791,
    "irating": 4.09,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 66. It covers the genre Thriller and is written by Author 66."
  },
  {
    "id": 67,
    "title": "Book Title 67",
    "author": "Author 67",
    "year": 1914,
    "genre": "Mystery",
    "pages": 778,
    "irating": 3.13,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 67. It covers the genre Thriller and is written by Author 67."
  },
  {
    "id": 68,
    "title": "Book Title 68",
    "author": "Author 68",
    "year": 1919,
    "genre": "Horror",
    "pages": 246,
    "irating": 3.76,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 68. It covers the genre Comic and is written by Author 68."
  },
  {
    "id": 69,
    "title": "Book Title 69",
    "author": "Author 69",
    "year": 1992,
    "genre": "Fiction",
    "pages": 175,
    "irating": 2.38,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 69. It covers the genre Fiction and is written by Author 69."
  },
  {
    "id": 70,
    "title": "Book Title 70",
    "author": "Author 70",
    "year": 2015,
    "genre": "Romantic",
    "pages": 512,
    "irating": 2.92,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 70. It covers the genre Comic and is written by Author 70."
  },
  {
    "id": 71,
    "title": "Book Title 71",
    "author": "Author 71",
    "year": 1907,
    "genre": "Horror",
    "pages": 796,
    "irating": 1.48,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 71. It covers the genre Thriller and is written by Author 71."
  },
  {
    "id": 72,
    "title": "Book Title 72",
    "author": "Author 72",
    "year": 1918,
    "genre": "Mystery",
    "pages": 523,
    "irating": 3.71,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 72. It covers the genre Romantic and is written by Author 72."
  },
  {
    "id": 73,
    "title": "Book Title 73",
    "author": "Author 73",
    "year": 1986,
    "genre": "Fantasy",
    "pages": 518,
    "irating": 2.89,
    "imageUrl": "https://i.imgur.com/9Y8Y8Y8.jpg",
    "description": "This is a dummy description for Book Title 73. It covers the genre Romantic and is written by Author 73."
  },
  {
    "id": 74,
    "title": "Book Title 74",
    "author": "Author 74",
    "year": 1918,
    "genre": "Thriller",
    "pages": 386,
    "irating": 2.68,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 74. It covers the genre Mystery and is written by Author 74."
  },
  {
    "id": 75,
    "title": "Book Title 75",
    "author": "Author 75",
    "year": 1910,
    "genre": "Horror",
    "pages": 752,
    "irating": 4.09,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 75. It covers the genre Comic and is written by Author 75."
  },
  {
    "id": 76,
    "title": "Book Title 76",
    "author": "Author 76",
    "year": 2001,
    "genre": "Mystery",
    "pages": 537,
    "irating": 3.11,
    "imageUrl": "https://i.imgur.com/5A5A5A5.jpg",
    "description": "This is a dummy description for Book Title 76. It covers the genre Comic and is written by Author 76."
  },
  {
    "id": 77,
    "title": "Book Title 77",
    "author": "Author 77",
    "year": 2005,
    "genre": "Sci-Fi",
    "pages": 661,
    "irating": 4.32,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 77. It covers the genre Fiction and is written by Author 77."
  },
  {
    "id": 78,
    "title": "Book Title 78",
    "author": "Author 78",
    "year": 1951,
    "genre": "Mystery",
    "pages": 252,
    "irating": 3.34,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 78. It covers the genre Romantic and is written by Author 78."
  },
  {
    "id": 79,
    "title": "Book Title 79",
    "author": "Author 79",
    "year": 1984,
    "genre": "Fiction",
    "pages": 746,
    "irating": 3.06,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 79. It covers the genre Fiction and is written by Author 79."
  },
  {
    "id": 80,
    "title": "Book Title 80",
    "author": "Author 80",
    "year": 1932,
    "genre": "Horror",
    "pages": 511,
    "irating": 1.56,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 80. It covers the genre Mystery and is written by Author 80."
  },
  {
    "id": 81,
    "title": "Book Title 81",
    "author": "Author 81",
    "year": 1932,
    "genre": "Fiction",
    "pages": 104,
    "irating": 1.31,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 81. It covers the genre Adventure and is written by Author 81."
  },
  {
    "id": 82,
    "title": "Book Title 82",
    "author": "Author 82",
    "year": 1996,
    "genre": "Horror",
    "pages": 401,
    "irating": 4.87,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 82. It covers the genre Romantic and is written by Author 82."
  },
  {
    "id": 83,
    "title": "Book Title 83",
    "author": "Author 83",
    "year": 2021,
    "genre": "Mystery",
    "pages": 299,
    "irating": 2.25,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 83. It covers the genre Horror and is written by Author 83."
  },
  {
    "id": 84,
    "title": "Book Title 84",
    "author": "Author 84",
    "year": 1931,
    "genre": "Comic",
    "pages": 465,
    "irating": 3.94,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 84. It covers the genre Fantasy and is written by Author 84."
  },
  {
    "id": 85,
    "title": "Book Title 85",
    "author": "Author 85",
    "year": 1910,
    "genre": "Thriller",
    "pages": 235,
    "irating": 2.0,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 85. It covers the genre Fiction and is written by Author 85."
  },
  {
    "id": 86,
    "title": "Book Title 86",
    "author": "Author 86",
    "year": 2020,
    "genre": "Thriller",
    "pages": 104,
    "irating": 2.21,
    "imageUrl": "https://i.imgur.com/QFDRuAh.jpg",
    "description": "This is a dummy description for Book Title 86. It covers the genre Romantic and is written by Author 86."
  },
  {
    "id": 87,
    "title": "Book Title 87",
    "author": "Author 87",
    "year": 1998,
    "genre": "Fantasy",
    "pages": 663,
    "irating": 2.26,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 87. It covers the genre Fantasy and is written by Author 87."
  },
  {
    "id": 88,
    "title": "Book Title 88",
    "author": "Author 88",
    "year": 2009,
    "genre": "Fantasy",
    "pages": 526,
    "irating": 3.77,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 88. It covers the genre Romantic and is written by Author 88."
  },
  {
    "id": 89,
    "title": "Book Title 89",
    "author": "Author 89",
    "year": 1930,
    "genre": "Fiction",
    "pages": 691,
    "irating": 2.21,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 89. It covers the genre Horror and is written by Author 89."
  },
  {
    "id": 90,
    "title": "Book Title 90",
    "author": "Author 90",
    "year": 1978,
    "genre": "Fiction",
    "pages": 740,
    "irating": 3.26,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 90. It covers the genre Adventure and is written by Author 90."
  },
  {
    "id": 91,
    "title": "Book Title 91",
    "author": "Author 91",
    "year": 1951,
    "genre": "Horror",
    "pages": 232,
    "irating": 1.67,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 91. It covers the genre Fantasy and is written by Author 91."
  },
  {
    "id": 92,
    "title": "Book Title 92",
    "author": "Author 92",
    "year": 1910,
    "genre": "Comic",
    "pages": 521,
    "irating": 2.16,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 92. It covers the genre Fantasy and is written by Author 92."
  },
  {
    "id": 93,
    "title": "Book Title 93",
    "author": "Author 93",
    "year": 1986,
    "genre": "Sci-Fi",
    "pages": 214,
    "irating": 1.54,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 93. It covers the genre Romantic and is written by Author 93."
  },
  {
    "id": 94,
    "title": "Book Title 94",
    "author": "Author 94",
    "year": 1983,
    "genre": "Horror",
    "pages": 739,
    "irating": 4.08,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 94. It covers the genre Horror and is written by Author 94."
  },
  {
    "id": 95,
    "title": "Book Title 95",
    "author": "Author 95",
    "year": 1964,
    "genre": "Romantic",
    "pages": 338,
    "irating": 1.83,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 95. It covers the genre Adventure and is written by Author 95."
  },
  {
    "id": 96,
    "title": "Book Title 96",
    "author": "Author 96",
    "year": 1950,
    "genre": "Thriller",
    "pages": 357,
    "irating": 3.36,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 96. It covers the genre Horror and is written by Author 96."
  },
  {
    "id": 97,
    "title": "Book Title 97",
    "author": "Author 97",
    "year": 2020,
    "genre": "Comic",
    "pages": 539,
    "irating": 1.4,
    "imageUrl": "https://i.imgur.com/2jMCqQ2.jpg",
    "description": "This is a dummy description for Book Title 97. It covers the genre Fiction and is written by Author 97."
  },
  {
    "id": 98,
    "title": "Book Title 98",
    "author": "Author 98",
    "year": 1942,
    "genre": "Adventure",
    "pages": 428,
    "irating": 2.19,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 98. It covers the genre Comic and is written by Author 98."
  },
  {
    "id": 99,
    "title": "Book Title 99",
    "author": "Author 99",
    "year": 2018,
    "genre": "Fantasy",
    "pages": 442,
    "irating": 3.68,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 99. It covers the genre Romantic and is written by Author 99."
  },
  {
    "id": 100,
    "title": "Book Title 100",
    "author": "Author 100",
    "year": 1989,
    "genre": "Fantasy",
    "pages": 107,
    "irating": 3.94,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 100. It covers the genre Sci-Fi and is written by Author 100."
  },
  {
    "id": 101,
    "title": "Book Title 101",
    "author": "Author 101",
    "year": 1968,
    "genre": "Comic",
    "pages": 201,
    "irating": 4.0,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 101. It covers the genre Thriller and is written by Author 101."
  },
  {
    "id": 102,
    "title": "Book Title 102",
    "author": "Author 102",
    "year": 1905,
    "genre": "Fiction",
    "pages": 213,
    "irating": 1.16,
    "imageUrl": "https://i.imgur.com/8yIIokW.jpg",
    "description": "This is a dummy description for Book Title 102. It covers the genre Mystery and is written by Author 102."
  },
  {
    "id": 103,
    "title": "Book Title 103",
    "author": "Author 103",
    "year": 1903,
    "genre": "Sci-Fi",
    "pages": 759,
    "irating": 2.44,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 103. It covers the genre Comic and is written by Author 103."
  },
  {
    "id": 104,
    "title": "Book Title 104",
    "author": "Author 104",
    "year": 1972,
    "genre": "Mystery",
    "pages": 279,
    "irating": 3.29,
    "imageUrl": "https://i.imgur.com/1C1C1C1.jpg",
    "description": "This is a dummy description for Book Title 104. It covers the genre Thriller and is written by Author 104."
  },
  {
    "id": 105,
    "title": "Book Title 105",
    "author": "Author 105",
    "year": 2014,
    "genre": "Fantasy",
    "pages": 796,
    "irating": 3.57,
    "imageUrl": "https://i.imgur.com/3B3B3B3.jpg",
    "description": "This is a dummy description for Book Title 105. It covers the genre Fiction and is written by Author 105."
  },
  {
    "id": 106,
    "title": "Book Title 106",
    "author": "Author 106",
    "year": 1940,
    "genre": "Romantic",
    "pages": 526,
    "irating": 1.76,
    "imageUrl": "https://i.imgur.com/KIPtISY.jpg",
    "description": "This is a dummy description for Book Title 106. It covers the genre Thriller and is written by Author 106."
  },
  {
    "id": 107,
    "title": "Book Title 107",
    "author": "Author 107",
    "year": 1926,
    "genre": "Comic",
    "pages": 181,
    "irating": 1.11,
    "imageUrl": "https://i.imgur.com/7Z6X6X6.jpg",
    "description": "This is a dummy description for Book Title 107. It covers the genre Mystery and is written by Author 107."
  },
  {
    "id": 108,
    "title": "Book Title 108",
    "author": "Author 108",
    "year": 1904,
    "genre": "Comic",
    "pages": 757,
    "irating": 2.73,
    "imageUrl": "https://i.imgur.com/pwpWaWu.jpg",
    "description": "This is a dummy description for Book Title 108. It covers the genre Horror and is written by Author 108."
  }
]


export default books;